### ISSUE TITLE
Fix toggle back to participant from admin

### ISSUE THREAD

**Issue by pelund** [TeamFlame/CS3733_AWS#18]

**Comment by pelund** [comment]
Found where it was going wrong, but not the fix. My guess is that it is happening around line 20 in admin.html. However, the href looks like it should work. 

I found [this](https://aws.amazon.com/premiumsupport/knowledge-center/404-error-nosuchkey-s3/)
whivh basically claims that the file that it is trying to access it misnamed or does not exist.

**Comment by pelund** [comment]
My fix did not work, problems continue as before

**Comment by SamTalpey** [comment]
When testing with the test.js file, the hrefs on both admin and the index files should be '/' or '/admin' due to how express paths the requests. For the live deployment, they should be './index.html' or './admin.html'. Past that there shouldn't be any issues.
